* JML
Line of computers built from scrap.

** Table of Contents :toc:
- [[#jml][JML]]
  - [[#design][Design]]
  - [[#parts][Parts]]
  - [[#folder-organization][Folder Organization]]
  - [[#families][Families]]

** Design
The line of *JML* computers is broken into "families". Each family is
designated by a number, for example the *JML-8* family of computer. Each model
in that family is further distinguished by a name, for example the
*JML-8-Mini*.

Each family of computers is designed so that all software is fully backwards
compatible between models.

** Parts
All parts have been scrapped from other computers/electronics. Many of these
parts are from very old computers and are no longer on the market.

Modern day equivalents do exist, but it is necessary to be cautious about
differing pin-outs. It may be necessary to design a new PCB for a modern
chip, or at least a way to change pin-out.

** Folder Organization
Information about the different model computers can be found in any
directory titled *JML-{family}-{model}*.

Various other [[file:related-projects][projects]] were useful in designing the computers. More
information can be found in the directory linked.

** Families
Below is a list of all families with a brief description of each family.

- [[JML-8]]

*** JML-8
This is a family of 8-bit microcomputers designed around the Z80
microprocessor.

- [[JML-8-Mini]]

**** JML-8-Mini
⚠ THIS MODEL IS STILL UNDER DEVELOPMENT.

[[File:jml-8-mini][This]] model uses a UART serial port to communicate with a terminal.
An FTDI chip can be used to send data from your computer to the
Z80. A [[file:related-projects/jml-terminal][specific terminal]] was created for use with this computer,
but other terminals will work just as well.

The "operating system" this model runs only allows for very simple
commands. These commands allow the user to read the values at
memory locations, write values to memory locations and transfer
program control to a specific memory location. More information
can be found at the [[file:jml-8-mini][linked directory]].
