* JML
Line of computers built from scrap.

** Design
The line of *JML* computers is broken into "families". Each family is
designated by a number, for example the *JML-8* family of computer. Each model
in that family is further distinguished by a name, for example the
*JML-8-Mini*.

Each family of computers is designed so that all software is fully backwards
compatible between models.

** Parts
All parts have been scrapped from other computers/electronics. Many of these
parts are from very old computers and are no longer on the market.

Modern day equivalents do exist, but it is necessary to be cautious about
differing pin-outs. It may be necessary to design a new PCB for a modern
chip, or a way to change pin-out.

** Folder Organization
Information about the different model computers can be found in any
directory titled *JML-{family}-{model}*.

Various other [[file:related-projects][projects]] were found to be useful. Many of these projects were
created by others, and links to those projects will be found in the
directory linked above.
