* jml Related Projects
This directory contains projects that were helpful in developing the *jml*
line of computers as well as "add-on" projects specifically designed for
the *jml* computers. Not all projects were done by me; those projects will
be linked. If they were developed by me, all code, etc. will be in this
directory.

These projects do not occur in any particular order.

** Arduino Z80 Debugger
This is a small Arduino-based project designed to capture output signals from 
a *Z80 CPU*

More details: [[./arduino-debugger][Arduino Z80 Debugger]].

** Arduino RAM Tester
This is a small Arduino-based project designed to test whether or not a ram IC
is working. The tests are very basic and not at all comprehensive.

More details: [[./ram-tester][Arduino RAM Tester]].

** AT28C EEPROM Programmer for Arduino Mega
This [[https://github.com/crmaykish/AT28C-EEPROM-Programmer-Arduino.git][project]] was created by *crmaykish* on GitHub. It was very useful for
programming the EEPROMs used in the *jml* computers.


# ** Text Editor
# This is a very simplistic text editor designed to be run on a *jml* computer.
# While it can, in theory, be run on a *jml-8*, it would not be useful, as there
# is no memory. As such, it is really meant for the *jml-8+* computer.

# More details: [[https://github.com/jac-oblong/text-editor][Text Editor]]
